inherit_from:
  - https://raw.githubusercontent.com/hanakai-rb/repo-sync/main/rubocop/rubocop.yml

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*_spec.rb"
  AllowedPatterns:
    # Allow comments
    - '\A\s*#'

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false
