#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

run_unit_tests() {
  bundle exec rake spec:coverage
}

run_isolation_tests() {
  local pwd=$PWD
  local root="$pwd/spec/isolation"

  run_tests $root
}

run_integration_tests() {
  local pwd=$PWD
  local root="$pwd/spec/integration"

  run_tests $root
}

run_tests() {
  local root=$1

  for test in $(find $root -name '*_spec.rb')
  do
    run_test $test

    if [ $? -ne 0 ]; then
      local exit_code=$?
      echo "Failing test: $test"
      exit $exit_code
    fi
  done
}

run_test() {
  local test=$1

  printf "\n\n\nRunning: $test\n"
  COVERAGE=true bundle exec rspec $test
}

main() {
  run_unit_tests &&
    run_isolation_tests &&
    run_integration_tests
}

main
