source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'sass'

gem 'hanami-utils',       '~> 0.6', github: 'hanami/utils',       branch: '0.6.x'
gem 'hanami-validations', '~> 0.3', github: 'hanami/validations', branch: '0.3.x'
gem 'hanami-router',      '~> 0.4', github: 'hanami/router',      branch: '0.5.x'
gem 'hanami-controller',  '~> 0.4', github: 'hanami/controller',  branch: '0.4.x'
gem 'hanami-view',        '~> 0.4', github: 'hanami/view',        branch: '0.4.x'
gem 'hanami-model',       '~> 0.5', github: 'hanami/model',       branch: '0.5.x'
gem 'hanami-helpers',     '~> 0.2', github: 'hanami/helpers',     branch: '0.2.x'
gem 'hanami-mailer',      '~> 0.1', github: 'hanami/mailer',      branch: '0.1.x'
gem 'hanami-assets',      '~> 0.1', github: 'hanami/assets',      branch: 'master'
gem 'hanami',                       path:   '../../..'

group :development do
  # Code reloading
  # See: [LINK TO HANAMI GUIDES]
  gem 'shotgun'
end

group :test, :development do
  gem 'dotenv', '~> 2.0'
end

group :test do
  gem 'minitest'
  gem 'capybara'
end

group :production do
  # gem 'puma'
end
