# frozen_string_literal: true

# This file is synced from hanakai-rb/repo-sync

name: RuboCop

on:
  push:
    branches: ["main", "release-*", "ci/*"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "release-*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: tools

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: Set up Ruby 4.0
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # zizmor: ignore[cache-poisoning]
        with:
          ruby-version: 4.0
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --parallel
